# Generated by Django 5.2.3 on 2025-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_contactmessage_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='service',
            name='durations_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='tip',
            name='delay',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
